#' Estimate infections, the time-varying reproduction number and the rate of
#' growth
#'
#' @description `r lifecycle::badge("maturing")`
#' Uses a renewal equation approach to estimate underlying latent infections
#' from reported cases, accounting for uncertain reporting delays and a
#' flexible observation model. Estimation is performed using the
#' [epinowcast](https://package.epinowcast.org/) package as a backend.
#'
#' @param data A `<data.frame>` of disease reports (confirm) by date (date).
#' `confirm` must be numeric and `date` must be in date format.
#'
#' @param generation_time A call to [gt_opts()] (or its alias
#' [generation_time_opts()]) defining the generation time distribution used.
#'
#' @param delays A call to [delay_opts()] defining delay distributions and
#' options. See the documentation of [delay_opts()] and the examples below for
#' details.
#'
#' @param rt A call to [rt_opts()] defining Rt estimation options. Currently
#' supports random walk models via `rw` parameter.
#'
#' @param obs A call to [obs_opts()] defining the observation model. Supports
#' `"negbin"` and `"poisson"` families.
#'
#' @param forecast A list of options as generated by [forecast_opts()] defining
#' the forecast options. Defaults to [forecast_opts()]. If NULL then no
#' forecasting will be done.
#'
#' @param stan A call to [stan_opts()] defining sampling options (number of
#' samples, chains, warmup).
#'
#' @param verbose Logical, defaults to `TRUE` when used interactively and
#' otherwise `FALSE`. Should verbose progress messages be printed.
#'
#' @param truncation `r lifecycle::badge("deprecated")` No longer supported.
#' @param backcalc `r lifecycle::badge("deprecated")` No longer supported.
#' @param gp `r lifecycle::badge("deprecated")` No longer supported.
#' @param id `r lifecycle::badge("deprecated")` No longer supported.
#'
#' @export
#' @return An `<estimate_infections>` object containing:
#'
#' - `fit`: The fitted model object.
#' - `args`: A list of arguments used for fitting.
#' - `observations`: The input data (`<data.frame>`).
#'
#' @seealso [get_samples()] [get_predictions()] [get_parameters()]
#' [epinow()] [regional_epinow()]
#' @importFrom checkmate assert_class assert_logical assert_string
#' @examples
#' \dontrun{
#' # set number of cores to use
#' old_opts <- options()
#' options(mc.cores = ifelse(interactive(), 4, 1))
#'
#' # get example case counts
#' reported_cases <- example_confirmed[1:40]
#'
#' # set an example generation time
#' generation_time <- Gamma(
#'   shape = Normal(1.3, 0.3),
#'   rate = Normal(0.37, 0.09),
#'   max = 14
#' )
#' # set an example reporting delay
#' reporting_delay <- LogNormal(mean = 2, sd = 1, max = 10)
#'
#' def <- estimate_infections(reported_cases,
#'   generation_time = gt_opts(generation_time),
#'   delays = delay_opts(reporting_delay),
#'   rt = rt_opts(rw = 7),
#'   stan = stan_opts(samples = 1000)
#' )
#' summary(def)
#' plot(def)
#' options(old_opts)
#' }
estimate_infections <- function(data,
                                generation_time = gt_opts(),
                                delays = delay_opts(),
                                rt = rt_opts(),
                                obs = obs_opts(),
                                forecast = forecast_opts(),
                                stan = stan_opts(),
                                verbose = interactive(),
                                truncation,
                                backcalc,
                                gp,
                                id) {
  # Deprecation messages for removed features
  enw_deprecation <- paste(
    "This feature is not supported in the epinowcast backend",
    "used since EpiNow2 v2.0.0."
  )
  if (!missing(gp)) {
    lifecycle::deprecate_stop(
      "2.0.0", "estimate_infections(gp)",
      details = paste(
        enw_deprecation,
        "Use rt_opts(rw = 7) for a weekly random walk as an alternative",
        "to Gaussian process smoothing."
      )
    )
  }
  if (!missing(backcalc)) {
    lifecycle::deprecate_stop(
      "2.0.0", "estimate_infections(backcalc)",
      details = paste(
        enw_deprecation,
        "Use the renewal model with rt_opts() instead."
      )
    )
  }
  if (!missing(truncation)) {
    lifecycle::deprecate_stop(
      "2.0.0", "estimate_infections(truncation)",
      details = paste(
        enw_deprecation,
        "Use estimate_truncation() to preprocess truncated data."
      )
    )
  }
  if (!missing(id)) {
    lifecycle::deprecate_warn("2.0.0", "estimate_infections(id)")
  }

  check_reports_valid(data, model = "estimate_infections")
  assert_class(generation_time, "generation_time_opts")
  assert_class(delays, "delay_opts")
  assert_class(rt, "rt_opts")
  assert_class(obs, "obs_opts")
  if (is.null(forecast)) {
    forecast <- forecast_opts(horizon = 0)
  }
  assert_class(forecast, "forecast_opts")
  assert_class(stan, "stan_opts")
  assert_logical(verbose)

  run_epinowcast(
    data = data,
    generation_time = generation_time,
    delays = delays,
    rt = rt,
    obs = obs,
    forecast = forecast,
    stan = stan,
    verbose = verbose
  )
}

#' Extract elements from estimate_infections objects with deprecation errors
#'
#' @description `r lifecycle::badge("deprecated")`
#' Provides backward compatibility for the old return structure. The previous
#' structure with \code{samples} and \code{summarised} elements is deprecated.
#' Use the accessor methods instead:
#' \itemize{
#'   \item \code{samples} - use \code{get_samples(object)}
#'   \item \code{summarised} - use \code{summary(object, type = "parameters")}
#' }
#'
#' @param x An \code{estimate_infections} object
#' @param name The name of the element to extract
#' @return The requested element. Errors for deprecated element names.
#' @keywords internal
#' @export
#' @method $ estimate_infections
`$.estimate_infections` <- function(x, name) {
  switch(name,
    samples = lifecycle::deprecate_stop(
      "1.9.0",
      I("estimate_infections()$samples"),
      "get_samples()"
    ),
    summarised = lifecycle::deprecate_stop(
      "1.9.0",
      I("estimate_infections()$summarised"),
      I("summary(type = 'parameters')")
    )
  )
  .subset2(x, name)
}

#' Extract elements from estimate_infections objects with bracket notation
#'
#' @description `r lifecycle::badge("deprecated")`
#' Provides backward compatibility for bracket-based access to deprecated
#' elements. See [$.estimate_infections] for details on the deprecation.
#'
#' @param x An `estimate_infections` object
#' @param i The name or index of the element to extract
#' @return The requested element. Errors for deprecated element names.
#' @keywords internal
#' @export
#' @method [[ estimate_infections
`[[.estimate_infections` <- function(x, i) {
  `$.estimate_infections`(x, i)
}
